### ISSUE TITLE
Simple example doesn't produce Java

### ISSUE THREAD

**Issue by TrustyPatches** [plum-umd/java-sketch#11]
I'm trying to run the simple example given in the paper and online, but no Java seems to be generated. 

My input files: 

```
class SimpleMath {
    static int mult2(int x) {
        return ?? * {| x , 0 |};
    }
}
```
```
class Test {
    harness static void test() {
        assert SimpleMath.mult2(3) == 6;
    }
}
```

Processed with the command: 

`./jsk.sh SimpleMath.java Test.java`

The end of the log output I show here (it stops after the 'sketch' phase): 

```
...
12:38:39 [INFO] java_sk/encoder.py:149 => generating main.sk
12:38:39 [INFO] java_sk/encoder.py:152 => writing struct Object
12:38:39 [INFO] java_sk/encoder.py:156 => generating array.sk
12:38:39 [INFO] /usr/local/bin/java-sketch/java_sk/main.py:64 => sk_dir: result/sk_SimpleTest, output_path: result/output/SimpleTest.txt
12:38:39 [INFO] java_sk/sketch.py:31 => sketch running...
sketch result/sk_SimpleTest/main.sk --fe-tempdir result --fe-keep-tmp --fe-output sk_SimpleTest --fe-inc result/sk_SimpleTest
12:38:39 [DEBUG] java_sk/sketch.py:35 => sketch result/sk_SimpleTest/main.sk --fe-tempdir result --fe-keep-tmp --fe-output sk_SimpleTest --fe-inc result/sk_SimpleTest
12:38:40 [INFO] java_sk/sketch.py:39 => sketch done: result/output/SimpleTest.txt
```

The paper suggests that processing should continue to generate the actual synthesised Java:

```
06:07:15 replacing holes
06:07:15 replacing generators
06:07:15 semantics checking
06:07:15 decoding result/java/SimpleMath.java
```

But I don't see any of this output, nor any `java` directory or `.java` files.

Is this functionality incomplete or am I looking in the wrong place? If it worked in a previous version I'd be grateful if you could point me to a working commit. 

Many thanks!

**Comment by TrustyPatches** [comment]
I guess this is covered by issue #7; excited to see the changes you guys have been working on once the compatibility issues with the new parser are fixed 😄 

In the meantime I'll work from commit 401d5fb (if you think this is sensible).

**Comment by bmarwritescode** [comment]
Yes, unfortunately this is still an issue. Hopefully this should be fixed soon. I am not sure about using that commit. I believe there were some bugs with dynamic dispatch in that commit, but I think those were only fixed after the switch to the new parser. Another option is to manually identify the hole values in the sketch output, though that approach is obviously not ideal.

**Comment by chaserhkj** [comment]
See #7 , the currently back-ported decoder can handle simple cases, so I'll close this issue for the time being and use that issue to track the status of more feature supports in the decoder.
