### ISSUE TITLE
documentation for expression generators

### ISSUE THREAD

**Issue by monperrus** [plum-umd/java-sketch#2]
Hi,

JSketch looks great. I'm interested in expression generators. I see two examples in the benchmark folder:
```
test/benchmarks/t107-miniTestb659.java:        d.next = {| c , b |};
test/benchmarks/t109-mult2.java:        return ?? * {| x , 0 |};
```

What's the exact meaning of {| c , b |}? How many and what type of operands are allowed?

**Comment by jsjeon** [comment]
The origin of that expression is Sketch's regular expression generators: see Section 4.2 in the [Sketch manual][m].  Alas, JSketch does not support the full regular expressions as Sketch does.

{| c , b |} in JSketch corresponds to {| c | b |} in Sketch, which simply means _choices_: Sketch can choose either variable c or b.  There is no limit on the number of operands, but the type of operands should agree.

[m]: http://people.csail.mit.edu/asolar/manual.pdf

**Comment by monperrus** [comment]
Thanks for the explanation.

In t101-miniTestb290.java, I'd like to replace
return h1 * x + h2 * y;
by
return ??;

such that Sketch generates an expression such as  x + y for instance.

How to do this?

**Comment by jsjeon** [comment]
Actually, the expected answer for that example is <code>x</code>.  Although I used <code>int</code> type for holes <code>h1</code> and <code>h2</code>, all possible combinations of <code>h1 * x + h2 * y</code> are: <code>{| x+y , x , y , 0 |}</code>.  Again, Sketch will pick <code>x</code>, not <code>x + y</code>.  See this commit: cd75085a78f6f98ad498216016b254a7e4554562.

**Comment by monperrus** [comment]
I see. Now, I change the test harness so that the expected answer is `return x+3y`. Can I get JSketch to generate ti from `return ??`?

**Comment by jsjeon** [comment]
No:  <code>??</code> is 32-bit bit vectors, hence the synthesis result will be just an integer, not an expression of a linear form with variables, etc.  If you want to synthesize an expression with variables, you should use regex generators, not simple holes.

**Comment by monperrus** [comment]
I see. I try to use a regex generator as follows. It works in sketch (without the `class`) but fails in jsketch. Any idea?

```
class Test {
harness void test( int x, int y, int z ){
   assert rec(x,y, z) == (x + y) ;
}

generator int rec(int x, int y, int z){ /* automatically rewritten */
   int t = ??;
   if(t == 0){
     return x;
   }   
   if(t == 1){
     return y;
   }

   if(t == 2){
     return z;
   }
   int a = rec(x,y,z);
   int b = rec(x,y,z);

   if(t == 3){
     return a * b;
   }

   if(t == 4){
     return a + b;
   } 
     
}
}
```

**Comment by jsjeon** [comment]
It looks like a different problem; could you please open a separate issue?  Thanks.

**Comment by monperrus** [comment]
done, see #3 

To really close this issue,  I'll see whether I can do PR on the README to explain all this.
