### ISSUE TITLE
custom codegen

### ISSUE THREAD

**Issue by jreeseue** [plum-umd/java-sketch#4]
What is the point of recompiling a custom codegen?

**Comment by jsjeon** [comment]
Not sure what the point of your question is, but here my best guess: I can't remember what Java and Sketch version I used to generate that pre-provided codegen jar.  Depending on the current Sketch version as well as your Java environment, you may need to rebuild custom codegen jar.

**Comment by jreeseue** [comment]
Ah, I think I understand. The custom codegen wasn't compiling for me, but I am running on a newer version of Sketch. I'll see what I can do about fixing this.
